/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNI_stub */

#ifndef _Included_JNI_stub
#define _Included_JNI_stub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_stub
 * Method:    nsetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1stub_nsetup
  (JNIEnv *, jobject);

/*
 * Class:     JNI_stub
 * Method:    nupdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1stub_nupdate
  (JNIEnv *, jobject);

/*
 * Class:     JNI_stub
 * Method:    ndraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1stub_ndraw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
