/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oftest */

#ifndef _Included_oftest
#define _Included_oftest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oftest
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oftest_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
