#!/bin/bash

tabletip=${1}

if [ -z "$tabletip" ];
then
	echo "Usage: $0 <tablet ip>"
	exit 1
fi

PIDFILE=/tmp/oscbroadcaster.pidlist
> $PIDFILE

$PFROOT/bin/oscbroadcast -s9001 -t osc.udp://localhost:9005 -t osc.udp://localhost:7002 -t osc.udp://localhost:7790 2> ../log/oscbroadcast9001.err.log > ../log/oscbroadcast9001.run.log &
echo $! >> $PIDFILE

$PFROOT/bin/oscbroadcast -s9998 -t osc.udp://${tabletip}:9998 -t osc.udp://127.0.0.1:7790 2> ../log/oscbroadcast9998.err.log > ../log/oscbroadcast9998.run.log &
echo $! >> $PIDFILE

$PFROOT/bin/oscbroadcast -s9999 -t osc.udp://localhost:7770 -t osc.udp://localhost:7002 -t osc.udp://localhost:7780 -t osc.udp://127.0.0.1:7790 2> ../log/oscbroadcast9999.err.log > ../log/oscbroadcast9999.run.log &
echo $! >> $PIDFILE



